AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  CertificateArn:
    Type: String
    Default: "arn:aws:iot:us-east-1:913094122452:cert/6efb3ab94972154bc12ccb7e88397cf11442d7ebef42c940bff2ab31df7170c5"
Resources:
  ParlorPalmThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: parlor-palm
  ParlorPalmPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref ParlorPalmThing
      Principal: !Ref CertificateArn
  PlantStatisticsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: PlantStatistics
      AttributeDefinitions: 
        - AttributeName: plant
          AttributeType: S
        - AttributeName: sampleDate
          AttributeType: S
      KeySchema: 
        - AttributeName: plant
          KeyType: HASH
        - AttributeName: sampleDate
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  TopicRuleRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - iot.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
  SaveParlorPalmRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: false
        Actions:
          - DynamoDBv2:
              RoleArn: !GetAtt TopicRuleRole.Arn
              PutItem:
                TableName: !Ref PlantStatisticsTable
          - CloudwatchMetric:
              RoleArn: !GetAtt TopicRuleRole.Arn
              MetricNamespace: Plants
              MetricName: parlor-palm-moisture
              MetricValue: "${moisture}"
              MetricUnit: None
        Sql: |
          select 
            topic(3) as plant,
            parse_time("yyyy-MM-dd'T'HH:mm:ssZ", (timestamp * 1000)) as sampleDate,
            current.state.desired.*,
          from "$aws/things/parlor-palm/shadow/update/documents"
